name: hutool:branch-1
on:
  push:
    branches:
    - branch-1
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [8]
        java-distribution: ['temurin']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java-distribution }}
      - run: bash <(curl -s https://codecov.io/bash)
